spring.application.name=backend

# =========================
# AIVEN MYSQL DATABASE
# =========================

spring.datasource.url=jdbc:mysql://mysql-2ee5f1b8-bhansalitejas07-a031.f.aivencloud.com:17781/defaultdb?sslMode=REQUIRED
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# =========================
# JPA / HIBERNATE
# =========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# =========================
# SERVER
# =========================

server.port=8080

# =========================
# SECURITY / JWT
# =========================

logging.level.org.springframework.security=TRACE

jwt.secret=MyVerySecretKeyForAgriConnectBackend123456789
jwt.expiration=86400000

# =========================
# LOGGING
# =========================

logging.level.org.springframework.web=DEBUG

logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=DEBUG

# =========================
# PRODUCT IMAGE UPLOAD
# =========================

file.upload-dir=uploads/products

# =========================
# FILE UPLOAD LIMITS
# =========================

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB